config/routes.rb
Rails.application.routes.draw do
  get '/first', to: "site#first", as: :first_page
  get '/second', to: "site#second", as: :second_page
  post '/third', to: "site#third", as: :third_page
  post '/fourth', to: "site#fourth", as: :fourth_page
  get '/frame', to: "site#frame", as: :frame_page
  get '/having_frame', to: "site#having_frame", as: :having_frame_page
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#first"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def first
  end

  def second
  end

  def third
  end

  def fourth
    Turbo::StreamsChannel.broadcast_update_to("mystr", target: "content", partial: "site/the_stuff")
  end

  def having_frame
  end

  def frame
    @what_is = [{"this": 23}]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboFramesVsTurboStreams</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="text-lg border-gray-200">
    <header>
      <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5">
        <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
          <a href="/" class="flex items-center">
            <span class="mr-4">🤓</span>
            <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">MegaSite</span>
          </a>
        </div>
      </nav>
    </header>
    <main class="container w-1/2 mx-auto mt-28 px-5 flex justify-center flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/site/_the_stuff.html.erb
<div class="py-4 mb-8 border text-center shadow-lg font-bold bg-white">
  <%= Time.now.strftime("%d %b %Y, %H:%M:%S") %>
</div>
<% 100.times do %>
  <p class="my-4"><%= Faker::Lorem.paragraph(sentence_count: 6) %></p>
<% end %>

app/views/site/first.html.erb
<%= turbo_stream_from "mystr" %>

<div class="w-full text-center my-8">
  <%= button_to "Load stuff!", fourth_page_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
</div>

<div class="my-8 w-full mx-auto" id="content">
  <%= render "the_stuff" %>
</div>

app/views/site/frame.html.erb
<%= turbo_frame_tag :mynewframe do %>
  <div>loaded!!!</div>

  <p>content in my new frame</p>
<% end %>

app/views/site/having_frame.html.erb
<turbo-frame id="mynewframe" src="<%= frame_page_path()  %>">
  <p>will load frame</p>
</turbo-frame>

<div id="mytarget">
</div>

<turbo-stream id="mmmcontent" action="update" target="mytarget" src="<%= third_page_path()  %>">
  <template>
    <p>hello templ</p>
    </template>
  <p>will load third</p>
  </turbo-frame>

app/views/site/second.html.erb
<%= render "the_stuff" %>

app/views/site/third.turbo_stream.erb
<%= turbo_stream.update "content" do %>
  <%= render "the_stuff" %>
<% end %>

<%= turbo_stream.before "content" do %>
  ADDED BEFORE
<% end %>